version: "3.8"

services:
  backend:
    build: .
    container_name: backend-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node index.js"
